name: Destroy infrastructure CI/CD
on:
  workflow_dispatch:

jobs:
  destroy_infrastructure:
    runs-on: azure
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: bash sync_cloud.sh
      env:
        TF_VAR_github_token: {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}
      run: bash sync_cloud.sh
    # - name: cleaning secrets
    #   run: for name_secret in `gcloud secrets list --filter={{cookiecutter.workspace}}- --uri`; do gcloud secrets delete -q $name_secret; done