name: Set up infrastructure CI/CD
on:
  workflow_dispatch:

jobs:
  set_up_infra:    
    runs-on: self-hosted
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: bash sync_cloud.sh
      env: 
        TF_VAR_github_token: {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}
      run: bash sync_cloud.sh
    - name: authorize gcp
      run: gcloud auth activate-service-account ${GOOGLE_IMPERSONATE_SERVICE_ACCOUNT} --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
    - name: set default project
      run: gcloud config set project "{{cookiecutter.project_id}}"
    - name: configure kubernetes connection
      run: gcloud container clusters get-credentials "{{cookiecutter.cluster_name}}-{{cookiecutter.workspace}}" --region "{{cookiecutter.region}}" --project "{{cookiecutter.project_id}}"
    - name: check pods number
      run: |
         repeat="true"
         wait_s=10
         max_retries=20
         while ${repeat} ; do
         pods_n=`kubectl get pods -n airflow | wc -l`
         if [ ${pods_n} -ge 5 ] ; then
          echo "Pods number - ok" && exit 0
         else
         ((i=i+1)) && echo "retries number ${i}" ; sleep ${wait_s}
          if [ ${i} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
          fi
         fi
         done      
    - name: check pods
      run: |
         max_retries=20
         for i in pgbouncer airflow-redis airflow-scheduler airflow-webserver airflow-worker ; do
         until kubectl wait --timeout=10s --for=condition=ready pods -n airflow -l app=$i
         do echo "waiting for $i"
            ((a=a+1)) && echo "retries number ${a}" 
            if [ ${a} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
            fi
         done
         done    
    - name: check webserver ip
      run: |
        echo "WEBSERVER_URL=$(kubectl get service airflow-webserver -n airflow -o jsonpath="{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}")" >> $GITHUB_ENV
    - name: show webserver URL
      run: {% raw %} echo "http://${{ env.WEBSERVER_URL }}" {% endraw %}
    - name: check webserver health
      run: |
         repeat="true"
         wait_s=10
         max_retries=30
         while ${repeat} ; do
         {% raw %} CHECK=`timeout 300 curl -s "http://${{ env.WEBSERVER_URL }}/api/v1/health" -H "content-type: application/json" | grep -w healthy | wc -l` {% endraw %}
         if [ ${CHECK} -eq 2 ] ; then
          echo "cluster is healthy" ; repeat="false"
         else
         ((i=i+1)) && echo "check number ${i} - cluster is not healthy yet" ; sleep ${wait_s}
          if [ ${i} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
          fi
         fi
         done
