name: Set up infrastructure CI/CD
on:
  workflow_dispatch:

env:
   WORKFLOW_ID: build_image_web.yaml
   {% if cookiecutter.nfs_dags!=None %}WORKSPACE_ACTION: add_dags.yaml
   {% endif %}

jobs:
  set_up_infra:    
    runs-on: [self-hosted,{{cookiecutter.labels}}]
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: finding a line number with a replica
      run: echo "NUMBER_LINE=$(expr `grep -n "taint        = \"worker\"" service/variables.tf | cut -f1 -d:` + 1)" >> $GITHUB_ENV;
    - name: replacing a number worker
      run: |
        if [[ `awk '/node_count   = 0/ && NR = $NUMBER_LINE' service/variables.tf` ]]
        then
          sed -i "${NUMBER_LINE} d" service/variables.tf
          sed -i "${NUMBER_LINE} s/^#//" service/variables.tf
          git pull
          git add service/variables.tf
          git config user.name "pause agent infra"
          git commit -m "start unpause infra [skip ci]"
          git push https://oauth2:{% raw %}${{ secrets.TF_VAR_GITHUB_TOKEN }}{% endraw %}@github.com/DsAirKube/{{ cookiecutter.workspace }}_infra_{{ cookiecutter.env }}.git
        else
          echo "replica is not set to 0" && exit 0
        fi
    - name: define repo path
      run: echo "GIT_REPO=$(echo ${GITHUB_REPOSITORY} | sed -e 's/infra_{{cookiecutter.env}}/app_{{cookiecutter.env}}/g')" >> $GITHUB_ENV
    - name: trigger build image
      run: |
         curl -X POST \
         -H "Authorization: token {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}" \
         --url https://api.github.com/repos/${GIT_REPO}/actions/workflows/${WORKFLOW_ID}/dispatches \
         -d '{"ref":"main"}'
    - name: bash sync_cloud.sh
      env: 
        TF_VAR_github_token: {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}
      run: bash sync_cloud.sh
    - name: change replicas in app
      run: |
        git clone https://oauth2:{% raw %}${{ secrets.TF_VAR_GITHUB_TOKEN }}{% endraw %}@github.com/{{ cookiecutter.org }}/{{ cookiecutter.workspace }}_app_{{ cookiecutter.env }}.git
        if [[ `grep -w "replicas: 0" {{ cookiecutter.workspace }}_app_{{ cookiecutter.env }}/yamles/airflow_worker_deployment.yaml` ]]
        then
          sed -i '/^  replicas\: 0/d' {{ cookiecutter.workspace }}_app_{{ cookiecutter.env }}/yamles/airflow_worker_deployment.yaml
          sed -i '/#  replicas/s/^#//' {{ cookiecutter.workspace }}_app_{{ cookiecutter.env }}/yamles/airflow_worker_deployment.yaml
          cd {{ cookiecutter.workspace }}_app_{{ cookiecutter.env }}
          git pull
          git add yamles/airflow_worker_deployment.yaml
          git config user.name "pause agent infra"
          git commit -m "start unpause infra [skip ci]"
          git push
          cd ..
        else
          echo "replica is not set to 0" && exit 0
        fi
    - name: set default project
      run: gcloud config set project "{{cookiecutter.project_id}}"
    - name: configure kubernetes connection
      run: gcloud container clusters get-credentials "{{cookiecutter.cluster_name}}-{{cookiecutter.workspace}}" --region "{{cookiecutter.region}}" --project "{{cookiecutter.project_id}}"
    - name: check pods number
      run: |
         repeat="true"
         wait_s=10
         max_retries=20
         while ${repeat} ; do
         pods_n=`kubectl get pods -n airflow | wc -l`
         if [ ${pods_n} -ge 5 ] ; then
          echo "Pods number - ok" && exit 0
         else
         ((i=i+1)) && echo "retries number ${i}" ; sleep ${wait_s}
          if [ ${i} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
          fi
         fi
         done      
    - name: check pods
      run: |
         wait_s=10
         max_retries=20
         for i in pgbouncer airflow-redis airflow-scheduler airflow-webserver airflow-worker ; do
         until kubectl wait --timeout=10s --for=condition=ready pods -n airflow -l app=$i
         do echo "waiting for $i"
            ((a=a+1)) && echo "retries number ${a}" ; sleep ${wait_s}
            if [ ${a} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
            fi
         done
         done    
    - name: check webserver ip
      run: |
        echo "WEBSERVER_URL=$(kubectl get service airflow-webserver -n airflow -o jsonpath="{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}")" >> $GITHUB_ENV
    - name: show webserver URL
      run: {% raw %} echo "https://${{ env.WEBSERVER_URL }}" {% endraw %}
    - name: check webserver health
      run: |
         repeat="true"
         wait_s=10
         max_retries=30
         while ${repeat} ; do
         {% raw %} CHECK=`timeout 300 curl -k "https://${{ env.WEBSERVER_URL }}/api/v1/health" -H "content-type: application/json" | grep -w healthy | wc -l` {% endraw %}
         if [ ${CHECK} -eq 2 ] ; then
          echo "cluster is healthy" ; repeat="false"
         else
         ((i=i+1)) && echo "check number ${i} - cluster is not healthy yet" ; sleep ${wait_s}
          if [ ${i} -eq ${max_retries} ] ; then
                echo "The maximum number of retries has been reached" && exit 1
          fi
         fi
         done
{% if cookiecutter.nfs_dags!=None %}
    - name: trigger copy dags on nfs
      run: |
         curl -X POST \
         -H "Authorization: token {% raw %}${{ secrets.TF_VAR_github_token }}{% endraw %}" \
         --url https://api.github.com/repos/{{ cookiecutter.org }}/{{ cookiecutter.workspace }}_workspace_data_{{ cookiecutter.env }}/actions/workflows/${WORKSPACE_ACTION}/dispatches \
         -d '{"ref":"main"}'
{% endif %}
